version: "3.3"

services:
  app:
    ports:
      - 6007:6007
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/storybook-static
      - /usr/src/app/build
      - /usr/src/app/.storybook
    